services:
  web:
    build: . # Docker akan mencari 'Dockerfile' di folder ini untuk membuat image aplikasi
    container_name: ads_backend 
    ports:
      - "8080:8080"
    env_file:
      - .env # Memasukkan variabel env ke aplikasi
    depends_on:
      - db # Memastikan database jalan duluan sebelum aplikasi start

  # 2. Service untuk Database PostgreSQL
  db:
    image: postgres:17-alpine
    container_name: ads_db
    restart: unless-stopped
    env_file:
      - .env # PostgreSQL akan membaca POSTGRES_USER, POSTGRES_PASSWORD, dan POSTGRES_DB dari sini
    ports:
      - "6969:5432" # Agar kamu tetap bisa remote database pakai DBeaver/PgAdmin dari laptop
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: # Menjaga agar data database tidak hilang saat container dimatikan