"""refactor claim to request and history

Revision ID: 833c79446d25
Revises: fda18c328af0
Create Date: 2026-05-30 13:29:49.680951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '833c79446d25'
down_revision: Union[str, None] = 'fda18c328af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # maaf aku copas ai capek banget
    # === 1. MANUAL UPDATE ENUM ITEMSTATUS ===
    # Hapus default lama agar tidak error saat alter type
    op.execute("ALTER TABLE items ALTER COLUMN status DROP DEFAULT")
    
    # Rename enum lama, buat enum baru dengan nilai UPPERCASE
    op.execute("ALTER TYPE itemstatus RENAME TO itemstatus_old")
    op.execute("CREATE TYPE itemstatus AS ENUM('RETURNED', 'NOT_RETURNED')")
    
    # Ubah tipe data di kolom menggunakan mapping (supaya data lama kalau ada bisa menyesuaikan)
    op.execute("""
        ALTER TABLE items 
        ALTER COLUMN status TYPE itemstatus 
        USING CASE 
            WHEN status::text IN ('returned', 'CLAIMED') THEN 'RETURNED'::itemstatus
            ELSE 'NOT_RETURNED'::itemstatus 
        END
    """)
    
    # Hapus enum lama & pasang default baru
    op.execute("DROP TYPE itemstatus_old")
    op.execute("ALTER TABLE items ALTER COLUMN status SET DEFAULT 'NOT_RETURNED'")
    # ========================================

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.Column('history_type', sa.Enum('REPORT', 'REQUEST', name='activityhistorykind'), nullable=False),
    sa.Column('request_type', sa.Enum('CLAIM', 'FOUND', name='requesttype'), nullable=True),
    sa.Column('item_status', sa.String(length=32), nullable=False),
    sa.Column('request_status', sa.String(length=32), nullable=True),
    sa.Column('report_type', sa.String(length=16), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_history_id'), 'activity_history', ['id'], unique=False)
    op.add_column('claim', sa.Column('request_type', sa.Enum('CLAIM', 'FOUND', name='requesttype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim', 'request_type')
    op.drop_index(op.f('ix_activity_history_id'), table_name='activity_history')
    op.drop_table('activity_history')
    # ### end Alembic commands ###

    # === MANUAL DOWNGRADE ENUM ITEMSTATUS ===
    op.execute("ALTER TABLE items ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TYPE itemstatus RENAME TO itemstatus_new")
    op.execute("CREATE TYPE itemstatus AS ENUM('not-returned', 'returned')")
    op.execute("""
        ALTER TABLE items 
        ALTER COLUMN status TYPE itemstatus 
        USING CASE 
            WHEN status::text = 'RETURNED' THEN 'returned'::itemstatus
            ELSE 'not-returned'::itemstatus 
        END
    """)
    op.execute("DROP TYPE itemstatus_new")
    op.execute("ALTER TABLE items ALTER COLUMN status SET DEFAULT 'not-returned'")
    # ========================================